import 'package:get/get.dart';

class LocalizationString extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'en_US': {
          'appName': 'Smart Grow',
          'appDescription': 'AI-Driven Crop Water Management System',
          'languageTitle': 'Select your language',
          'greeting1': 'Good Morning',
          'greeting2': 'Good Afternoon',
          'greeting3': 'Good Night',
          'startButton': 'Start',
          'login': 'Login',
          'loginTitle': 'Enter your mobile number',
          'loginTextFieldHintText': 'Phone number',
          'getOtpButton': 'Get OTP',
          'otpTitle': 'Verify the OTP',
          'otpDescription': 'Enter the 6 digit key in your phone message',
          'otpResnd': 'Resend the OTP',
          'userTitle': 'User details',
          'firstName': 'First Name',
          'firstNameVoiceCommand': 'Enter your first name',
          'lastName': 'Last Name',
          'lastNameVoiceCommand': 'Enter your last name',
          'email': 'E-mail Address',
          'emailVoiceCommand': 'Enter your email address',
          'cropName': 'Crop Name',
          'paddy': 'Paddy',
          'wheat': 'Wheat',
          'peas': 'Peas',
          'kidneyBeans': 'Kidney beans',
          'landDetails': 'Land details',
          'landUnit': 'Unit',
          'cent': 'Cent',
          'sqft': 'Sqft',
          'acres': 'Acres',
          'yourAddress': 'Your address',
          'address': 'Enter your address',
          'submitButton': 'Submit',
          'homeNav': 'Home',
          'reportNav': 'Report',
          'profile': 'Profile',
          'weatherCardTitle': "Today's weather",
          'weatherCardHumidity': 'Humidity',
          'weatherCardSuggestion': 'Today is a good day to use pesticides',
          'weatherPageTitle': 'Weather report',
          'temperature': 'Temperature',
          'soilmoisture': 'Soil moisture',
          'tempReportTitle': 'Current Temperature',
          'avgTemp': 'Average temperature',
          'minTemp': 'Minimal',
          'maxTemp': 'Very high',
          'humdityTitle': 'Wet base',
          'avgHumidity': 'Average humidity',
          'minHumidity': 'Minimal',
          'maxHumidity': 'Very High',
          'avgMoisture': 'Average Moisture',
          'minMoisture': 'Minimal',
          'maxMoisture': 'Very High',
          'motorSwitch': 'Motor switch',
          'todaysTask': "Today's task",
          'todayTaskTitle': 'Motor 1 is running',
          'todayTaskTitle2': 'Motor 2 will run',
          'reportTitle': 'Report',
          'titleMoisture': 'Soil Moisture',
          'titleMotorFlow': 'Motor Waterflow',
          'titleFieldFlow': 'Field Waterflow',
          'report1': 'Task 1',
          'reportActivity': 'Turn the motor on/off',
          'taskInputTitle': 'Create a new task',
          'taskInput1': 'Job title',
          'workActivity': 'Work activity',
          'date': 'Date',
          'time': 'Time',
          'remind': 'Remind me everyday',
          'description': 'Description',
          'createButton': 'Create',
          'previousTask': 'Previous Task',
          'completed': 'Completed',
          'profileTitle': 'Profile',
          'editiProfile': 'Edit profile',
          'logout': 'Logout',
          'descriptionContent':
              'A crop is a plant or plant product that can be grown and harvested for profit or for subsistence. ',
          'setting': 'Setting',
          'userManagement': 'User Management',
          'Information': 'Information',
          'language': 'Language',
        },
        'ta_IN': {
          'appName': 'ஸ்மார்ட் க்ரோ',
          'appDescription': 'AI-உந்துதல் பயிர் நீர் மேலாண்மை அமைப்பு',
          'languageTitle': 'உங்கள் மொழியைத் தேர்ந்தெடுக்கவும்',
          'greeting1': 'காலை வணக்கம்',
          'greeting2': 'மதிய வணக்கம்',
          'greeting3': 'இனிய இரவு',
          'startButton': 'தொடங்கு',
          'login': 'உள்நுழைய',
          'loginTitle': 'உங்களுடைய கைபேசி எண்ணை உள்ளிடவும்',
          'loginTextFieldHintText': 'தொலைபேசி எண்',
          'getOtpButton': 'OTP பெறவும்',
          'otpTitle': 'OTP ஐ சரிபார்க்கவும்',
          'otpDescription':
              'உங்கள் தொலைபேசி செய்தியில் 6 இலக்க விசையை உள்ளிடவும்',
          'otpResnd': 'OTP ஐ மீண்டும் அனுப்பவும்',
          'userTitle': 'பயனர் விவரங்கள்',
          'firstName': 'முதல் பெயர்',
          'firstNameVoiceCommand': 'உங்கள் முதல் பெயரை உள்ளிடவும்',
          'lastName': 'கடைசி பெயர்',
          'lastNameVoiceCommand': 'உங்கள் கடைசி பெயரை உள்ளிடவும்',
          'email': 'மின்னஞ்சல் முகவரி',
          'emailVoiceCommand': 'உங்கள் மின்னஞ்சல் முகவரியை உள்ளிடவும்',
          'cropName': 'பயிர் பெயர்',
          'paddy': 'நெல்',
          'wheat': 'கோதுமை',
          'peas': 'பட்டாணி',
          'kidneyBeans': 'சிறுநீரக பீன்ஸ்',
          'landDetails': 'நில விவரங்கள்',
          'landUnit': 'அலகு',
          'cent': 'சதம்',
          'sqft': 'சதுர அடி',
          'acres': 'ஏக்கர்',
          'yourAddress': 'உங்கள் முகவரி',
          'address': 'உங்கள் முகவரியை உள்ளிடவும்',
          'submitButton': 'சமர்ப்பிக்கவும்',
          'homeNav': 'வீடு',
          'reportNav': 'அறிக்கை',
          'profile': 'சுயவிவரத்தை',
          'weatherCardTitle': "இன்றைய வானிலை",
          'weatherCardHumidity': 'ஈரப்பதம்',
          'weatherCardSuggestion':
              'இன்று பூச்சிக்கொல்லி மருந்துகளை பயன்படுத்த நல்ல நாள்',
          'weatherPageTitle': 'வானிலை அறிக்கை',
          'temperature': 'வெப்ப நிலை',
          'soilmoisture': 'மண்ணின் ஈரப்பதம்',
          'tempReportTitle': 'தற்போதைய வெப்பநிலை',
          'avgTemp': 'சராசரி வெப்பநிலை',
          'minTemp': 'குறைந்தபட்சம்',
          'maxTemp': 'மிக அதிக',
          'humdityTitle': 'ஈரமான அடித்தளம்',
          'avgHumidity': 'சராசரி ஈரப்பதம்',
          'minHumidity': 'குறைந்தபட்சம்',
          'maxHumidity': 'மிக அதிக',
          'avgMoisture': 'சராசரி ஈரப்பதம்',
          'minMoisture': 'குறைந்தபட்சம்',
          'maxMoisture': 'மிக அதிக',
          'motorSwitch': 'மோட்டார் சுவிட்ச்',
          'todaysTask': "இன்றைய பணி",
          'todayTaskTitle': 'மோட்டார் 1 இயங்குகிறது',
          'todayTaskTitle2': 'மோட்டார் 2 இயங்கும்',
          'reportTitle': 'அறிக்கை',
          'titleMoisture': 'மண்ணின் ஈரப்பதம்',
          'titleMotorFlow': 'மோட்டார் நீர் ஓட்டம்',
          'titleFieldFlow': 'வயல் நீர் ஓட்டம்',
          'report1': 'பணி 1',
          'reportActivity': 'மோட்டாரை ஆன்/ஆஃப் செய்யவும்',
          'taskInputTitle': 'புதிய பணியை உருவாக்கவும்',
          'taskInput1': 'வேலை தலைப்பு',
          'workActivity': 'வேலை செயல்பாடு',
          'date': 'தேதி',
          'time': 'நேரம்',
          'remind': 'தினமும் எனக்கு நினைவூட்டு',
          'description': 'விளக்கம்',
          'createButton': 'உருவாக்கு',
          'previousTask': 'முந்தைய பணி',
          'completed': 'நிறைவு',
          'profileTitle': 'சுயவிவரம்',
          'editiProfile': 'சுயவிவரத்தைத் திருத்தவும்',
          'logout': 'வெளியேறு',
          'descriptionContent':
              'ஒரு பயிர் என்பது ஒரு தாவரம் அல்லது தாவர தயாரிப்பு ஆகும், இது இலாபத்திற்காக அல்லது வாழ்வாதாரத்திற்காக வளர்க்கப்பட்டு அறுவடை செய்யப்படலாம்.',
          'setting': 'அமைப்புகள்',
          'userManagement': 'பயனர் மேலாண்மை',
          'Information': 'தெரிவிப்பு',
          'language': 'மொழி'
        },
        'hi_IN': {
          'greeting1': 'शुभ प्रभात',
          'greeting2': 'शुभ दोपहर',
          'greeting3': 'शुभ रात्रि',
          'appName': 'स्मार्ट ग्रो',
          'appDescription': 'एआई-प्रेरित फसल जल प्रबंधन प्रणाली',
          'languageTitle': 'अपनी भाषा चुनें',
          'startButton': 'शुरू',
          'login': 'लॉग इन करें',
          'loginTitle': 'अपना मोबाइल नंबर दर्ज करें',
          'loginTextFieldHintText': 'फोन नंबर',
          'getOtpButton': 'OTP प्राप्त करें',
          'otpTitle': 'OTP सत्यापित करें',
          'otpDescription': 'अपने फोन संदेश में 6 अंकों को दर्ज करें',
          'otpResnd': 'OTP को फिर से भेजें',
          'userTitle': 'उपयोगकर्ता विवरण',
          'firstName': 'पहला नाम',
          'firstNameVoiceCommand': 'अपना पहला नाम दर्ज करें',
          'lastName': 'अंतिम नाम',
          'lastNameVoiceCommand': 'अपना अंतिम नाम दर्ज करें',
          'email': 'ई-मेल पता',
          'emailVoiceCommand': 'अपना ईमेल पता दर्ज करें',
          'cropName': 'फसल का नाम',
          'paddy': 'धान',
          'wheat': 'गेहूं',
          'peas': 'मटर',
          'kidneyBeans': 'राजमा',
          'landDetails': 'भूमि का विवरण',
          'landUnit': 'इकाई',
          'cent': 'सेंट',
          'sqft': 'वर्ग फीट',
          'acres': 'एकड़',
          'yourAddress': 'आपका पता',
          'address': 'अपना पता दर्ज करें',
          'submitButton': 'प्रस्तुत करें',
          'homeNav': 'होम',
          'reportNav': 'रिपोर्ट',
          'profile': 'प्रोफाइल',
          'weatherCardTitle': 'आज का मौसम',
          'weatherCardHumidity': 'आर्द्रता',
          'weatherCardSuggestion':
              'आज खेतों में कीटनाशक उपयोग करने के लिए एक अच्छा दिन है',
          'weatherPageTitle': 'मौसम रिपोर्ट',
          'temperature': 'तापमान',
          'soilmoisture': 'मृदा की आर्द्रता',
          'tempReportTitle': 'वर्तमान तापमान',
          'avgTemp': 'औसत तापमान',
          'minTemp': 'न्यूनतम',
          'maxTemp': 'अधिक',
          'humdityTitle': 'गीला आधार',
          'avgHumidity': 'औसत आर्द्रता',
          'minHumidity': 'न्यूनतम',
          'maxHumidity': 'अधिक',
          'descriptionContent':
              'एक फसल एक पौधा या पौधा उत्पाद है जिसे लाभ के लिए या निर्वाह के लिए उगाया और काटा जा सकता है।',
          'setting': 'सेटिंग',
          'userManagement': 'उपयोगकर्ता प्रबंधन',
          'Information': 'जानकारीपूर्ण',
          'language': 'भाषा'
        },
      };
}
